/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary:                    '#964328',
        'on-primary':               '#ffffff',
        'primary-container':        '#b55b3e',
        'on-primary-container':     '#fffbff',
        'primary-fixed':            '#ffdbd0',
        'primary-fixed-dim':        '#ffb59e',
        'on-primary-fixed':         '#3a0b00',
        'on-primary-fixed-variant': '#7a2f15',
        'inverse-primary':          '#ffb59e',
        secondary:                  '#5d5e64',
        'on-secondary':             '#ffffff',
        'secondary-container':      '#dfdfe6',
        'on-secondary-container':   '#616268',
        tertiary:                   '#735c00',
        'on-tertiary':              '#ffffff',
        'tertiary-container':       '#cba72f',
        'on-tertiary-container':    '#4e3d00',
        'tertiary-fixed':           '#ffe088',
        error:                      '#ba1a1a',
        'on-error':                 '#ffffff',
        'error-container':          '#ffdad6',
        surface:                    '#fbf9f4',
        'surface-dim':              '#dbdad5',
        'surface-bright':           '#fbf9f4',
        'surface-container-lowest': '#ffffff',
        'surface-container-low':    '#f5f3ee',
        'surface-container':        '#f0eee9',
        'surface-container-high':   '#eae8e3',
        'surface-container-highest':'#e4e2dd',
        'on-surface':               '#1b1c19',
        'on-surface-variant':       '#55433d',
        'inverse-surface':          '#30312e',
        'inverse-on-surface':       '#f2f1ec',
        outline:                    '#88726c',
        'outline-variant':          '#dbc1b9',
        background:                 '#fbf9f4',
        'on-background':            '#1b1c19',
        'surface-variant':          '#e4e2dd',
      },
      fontFamily: {
        sans:  ['Work Sans', 'system-ui', 'sans-serif'],
        serif: ['Libre Caslon Text', 'Georgia', 'serif'],
      },
      maxWidth: {
        container: '1200px',
      },
      screens: {
        xs: '480px',
      },
    },
  },
}
